### ISSUE TITLE
Eclipse SmartHome Designer

### ISSUE THREAD

**Issue by probonopd** [fusion809/AppImages#6]
Can you provide an AppImage for Eclipse SmartHome Designer, http://www.eclipse.org/smarthome/documentation/community/downloads.html?

http://www.eclipse.org/downloads/download.php?file=/smarthome/releases/0.8.0/eclipsesmarthome-incubation-0.8.0-designer-linux64.zip

**Comment by fusion809** [comment]
Could you provide me with an icon for SmartHome? After all without it the build fails giving the error:

```desktop
Desktop file: /home/fusion809/GitHub/mine/packaging/AppImages/recipes/meta/smarthome/eclipse-smarthome/eclipse-smarthome.AppDir/eclipse-smarthome.desktop
Name: Eclipse smarthome IDE
Icon: eclipse-smarthome
Exec: SmartHome-Designer.wrapper
Comment entry not found in desktop file
Comment: (null)
Type: Application
Categories: Development;IDE;smarthome
File used for determining architecture: /proc/self/exe
Arch: 86_64
App name for filename: Eclipse_smarthome_IDE
dest_path: Eclipse_smarthome_IDE-x86_64.AppImage
DESTINATION not specified, so assuming Eclipse_smarthome_IDE-0.8.0.glibc2.4-x86_64.AppImage

/home/fusion809/GitHub/mine/packaging/AppImages/recipes/meta/smarthome/eclipse-smarthome/eclipse-smarthome.AppDir should be packaged as Eclipse_smarthome_IDE-0.8.0.glibc2.4
-x86_64.AppImage
eclipse-smarthome{.png,.svg,.svgz,.xpm} not present but defined in desktop file
```

**Comment by probonopd** [comment]
Thanks for looking into it @fusion809 

Since I didn't find one immediately, a workaround might be to
```
wget "https://pbs.twimg.com/profile_images/378800000699017975/a2f977db2b9ede29fabb70c501261d3f_400x400.png"
sudo apt-get install imagemagick
convert *400x400.png -resize 128x128 icon.png
```

The proper thing to do would be to open an issue upstream asking for an icon to be included in the download (and a desktop file), but I don't have the time to sign up there and do that right now.

**Comment by fusion809** [comment]
Here is the AppImage you wanted, I haven't tested it yet (as I can't build it on my machine as I'm now using Fedora 25 as my primary OS and not a Debian-based distro wherein the apt commands can be understood) https://bintray.com/fusion809/AppImages/Eclipse_smarthome_IDE#files.

**Comment by probonopd** [comment]
Thank you very much @fusion809

**Comment by probonopd** [comment]
Getting

```
!ENTRY org.eclipse.osgi 4 0 2017-01-29 13:53:49.796
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: The platform metadata area could not be written: /tmp/.mount_xvfKF4/usr/workspace/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
	at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:61)
	at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:129)
	at org.eclipse.core.internal.preferences.InstancePreferences.getBaseLocation(InstancePreferences.java:44)
	at org.eclipse.core.internal.preferences.InstancePreferences.initializeChildren(InstancePreferences.java:199)
	at org.eclipse.core.internal.preferences.InstancePreferences.<init>(InstancePreferences.java:59)
	at org.eclipse.core.internal.preferences.InstancePreferences.internalCreate(InstancePreferences.java:209)
	at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:391)
	at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:379)
	at org.eclipse.core.internal.preferences.PreferencesService.createNode(PreferencesService.java:389)
	at org.eclipse.core.internal.preferences.RootPreferences.getChild(RootPreferences.java:63)
	at org.eclipse.core.internal.preferences.RootPreferences.getNode(RootPreferences.java:101)
	at org.eclipse.core.internal.preferences.RootPreferences.node(RootPreferences.java:90)
	at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
	at org.eclipse.core.runtime.preferences.InstanceScope.getNode(InstanceScope.java:80)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.getStorePreferences(ScopedPreferenceStore.java:244)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.<init>(ScopedPreferenceStore.java:133)
	at org.eclipse.ui.plugin.AbstractUIPlugin.getPreferenceStore(AbstractUIPlugin.java:285)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:593)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.smarthome.designer.ui.internal.application.Application.start(Application.java:32)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

The platform metadata area could not be written: __/tmp/.mount_xvfKF4/usr/workspace/.metadata__.  By default the platform writes its content under the current working directory when the platform is launched.  of course this doesn't work in a read-only AppImage. Hence we need to use a custom `*.desktop` file or `AppRun` script to set the `-data` parameter to specify a different content area for the platform.

**Comment by fusion809** [comment]
Well any patches you have for me (like in the form of pull requests) I'll be happy to accept.

**Comment by probonopd** [comment]
I am investigating; setting it to $HOME does not work either. Not sure what needs do be done, I need to investigate.
